name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        arch: [ i686 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo

      - name: Generate build
        run: cmake --preset ${{ matrix.arch }}

      - name: Build/Restore toolchain
        run: cmake --build --preset ${{ matrix.arch }} --target toolchain

      - name: Build system
        run: cmake --build --preset ${{ matrix.arch }} --target all

      - name: Install system
        run: cmake --build --preset ${{ matrix.arch }} --target install
