name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [i686]
        toolchain: [gnu]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev ninja-build ccache rsync unzip texinfo libssl-dev fuse2fs

      - name: Toolchain cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Binary/Cache/toolchain-${{ matrix.arch }}-${{ matrix.toolchain }}.tar.gz
          key: ${{ runner.os }}-toolchain-${{ matrix.arch }}-${{ hashFiles('Meta/Scripts/Toolchain/*.sh', 'Meta/Patches/*.patch', 'Libraries/C/**/*.h') }}

      - name: Compile system
        run: USE_CACHE=true Meta/Scripts/Nashios.sh build ${{ matrix.arch }} ${{ matrix.toolchain }}

      - name: Install system
        run: Meta/Scripts/Nashios.sh install ${{ matrix.arch }} ${{ matrix.toolchain }}
