name: Doxygen
on: [push]

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install cmake doxygen graphviz

            - name: Configure
              run: cmake --preset i686

            - name: Compile
              run: cmake --build --preset i686 --target doxygen

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: ${{ github.workspace }}/binary/build/doxygen/html
                repository-name: nashios/doxygen
                branch: main
                token: ${{ secrets.NASHIBOT_TOKEN }}